/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SortMethod = IDL.Variant({
  'byName' : IDL.Null,
  'byPhone' : IDL.Null,
});
export const OptionalSortMethod = IDL.Opt(SortMethod);
export const UserId = IDL.Principal;
export const Email = IDL.Text;
export const Phone = IDL.Text;
export const ContactSubmissionData = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(Email),
  'message' : IDL.Text,
  'phone' : Phone,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'data' : ContactSubmissionData,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSubmissions' : IDL.Func(
      [OptionalSortMethod],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubmissionById' : IDL.Func([IDL.Nat], [ContactSubmission], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, Phone, IDL.Opt(Email), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SortMethod = IDL.Variant({ 'byName' : IDL.Null, 'byPhone' : IDL.Null });
  const OptionalSortMethod = IDL.Opt(SortMethod);
  const UserId = IDL.Principal;
  const Email = IDL.Text;
  const Phone = IDL.Text;
  const ContactSubmissionData = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(Email),
    'message' : IDL.Text,
    'phone' : Phone,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'data' : ContactSubmissionData,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSubmissions' : IDL.Func(
        [OptionalSortMethod],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubmissionById' : IDL.Func([IDL.Nat], [ContactSubmission], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, Phone, IDL.Opt(Email), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };